CareerCradle/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

app_name = 'CareerCradle'

urlpatterns = [
    path('', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

candidates/urls.py
from django.urls import path
from .views import CandidateHomeView, JobsAppliedView
from .views import JobsView


app_name = 'candidates'

urlpatterns = [
    path('home/', CandidateHomeView.as_view(), name='home'),
    path('home/avail_jobs/',JobsView.as_view(), name = "avail_jobs"),
    path('Dashboard/', JobsAppliedView.as_view(), name="dashboard")
]

recruiters/urls.py
from django.urls import path
from .views import RecruiterHomeView, JobsPostedView


app_name = 'recruiters'

urlpatterns = [
    path('home/', RecruiterHomeView.as_view(), name='home'),
    path('home/dashboard/', JobsPostedView.as_view(), name='jobs_posted'),
]

users/urls.py
from django.urls import path
from .views import UsertypeRedirectView, FillUsertypeView, AboutUsView, ContactUsView

app_name = 'users'

urlpatterns = [
    path('redirect', UsertypeRedirectView.as_view(), name='redirect'),
    path('usertype', FillUsertypeView.as_view(), name='usertype'),
    path('about/', AboutUsView.as_view(), name='aboutus'),
    path('contact/', ContactUsView.as_view(), name='contactus'),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser,    BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.db.models import BooleanField

class UserManager(BaseUserManager):

    def _create_user(self, email, password, usertype, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            usertype=usertype,
            is_staff=is_staff, 
            is_active=True,
            is_superuser=is_superuser, 
            last_login=now,
            date_joined=now, 
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_candidate(self, email, password, **extra_fields):
        return self._create_user(email, password, 1, False, False, **extra_fields)

    def create_recruiter(self, email, password, **extra_fields):
        return self._create_user(email, password, 0, False, False, **extra_fields)

    def create_staff(self, email, password, **extra_fields):
        return self._create_user(email, password, None, True, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user=self._create_user(email, password, None, True, True, **extra_fields)
        user.save(using=self._db)
        return user

class User(AbstractBaseUser, PermissionsMixin):
    '''
    Usertype can have 3 values:
        Candidate - 1
        Recruiter - 0
        Staff - None
    '''
    USERTYPES = [
        (1, 'Candidates'),
        (0, 'Recruiters'),
        (None, 'Staff'),
    ]

    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254, null=True, blank=True)
    usertype = models.PositiveSmallIntegerField(choices=USERTYPES, null=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)

users/forms.py
from django.contrib.auth.models import User
from django import forms
from allauth.account.forms import SignupForm

class LoginForm(forms.ModelForm):
    '''Simple login form'''
    class Meta:
        model = User
        fields = ('username', 'password')


class MyCustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(MyCustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['usertype'] = forms.ChoiceField(choices=[(1, "Candidate"),
                                                             (0, "Recruiter")],
                                                    widget=forms.RadioSelect(attrs={'class':'usertype_radio'}))

    def save(self, request):
        user = super(MyCustomSignupForm, self).save(request)
        user.usertype = self.cleaned_data.pop('usertype')
        user.save()
        return user
        

class UserTypeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(UserTypeForm, self).__init__(*args, **kwargs)
        self.fields['usertype'] = forms.ChoiceField(choices=[(1, "Candidate"),
                                                             (0, "Recruiter")],
                                                    widget=forms.RadioSelect)
    
    def save(self, request):
        user = request.user
        user.usertype = self.cleaned_data.pop('usertype')
        user.save()
        return user

        

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LoginForm
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormView
from .models import User
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from .forms import UserTypeForm

# Create your views here.
class AuthView(TemplateView):

    def get(self, request):
        context = {
            'login_form': LoginForm(),
            'signup_form': UserCreationForm(request.POST or None),
        }
        return render(request, 'auth.html', context)

    def post(self, request):
        
        return render(request, 'select.html')

class SelectView(TemplateView):

    def get(self, request):
        return render(request, 'select.html')


class UsertypeRedirectView(LoginRequiredMixin, View):

    def get(self, request):
        current_user = request.user
        if current_user.usertype == 1: # Candidate
            return HttpResponseRedirect(reverse("candidates:home"))
        elif current_user.usertype == 0: # Recruiter
            return HttpResponseRedirect(reverse("recruiters:home"))
        elif not current_user.is_staff:
            return HttpResponseRedirect(reverse("users:usertype"))
            
        return HttpResponseForbidden()

class FillUsertypeView(LoginRequiredMixin, View):
    
    def get(self, request):
        current_user = request.user
        if current_user.usertype:
            return HttpResponseRedirect(reverse("users:redirect"))
        else:
            context = {
                'usertype_form': UserTypeForm(),
            }
            return render(request, "users/usertype.html", context)

    def post(self, request):
        user_type_form = UserTypeForm(request.POST)
        if user_type_form.is_valid():
            user_type_form.save(request)
        return HttpResponseRedirect(reverse("users:redirect"))

        
class ContactUsView(TemplateView):
    template_name = "users/contact.html"

class AboutUsView(TemplateView):
    template_name = "users/about.html"

templates/users/about.html
{% extends 'users/base_main.html' %}
{% load  static %}

{%	block	title	%}About{%	endblock	%}

{% block custom_scripts_n_links %}
<link rel="stylesheet" href= " {% static 'css/about.css' %}" />
{% endblock %}

{%block Welcome_block %}{% endblock %}

{% block content%}

    <section id="about-container">
        <h1 class="h-primary center">About-Us</h1>
        <div id="about">
            <div class="box">
                <img src="{% static 'images/Cc.png' %}" alt="">
                    <br>
                <p class="center">Career Cradle is a website, where Job-seekers,
                    Students, Interns can come to in order to start their career properly. Career Cradle can be
                    used to gain guidance from industry professionals and stay in contact with them. Career
                    Cradle has only purpose that is to give our society well-trained professionals and give the
                    qualified professionals the job they truly deserve. When a person has a job they like, it acts as
                    an emotional, social and financial support in their live and Career Cradle seeks to help in the
                    betterment of the society by providing people with stability.
                    </p>
            </div>
        </div>
    </section>

{% endblock %}

    

templates/users/auth.html
<h1> Welcome to CareerCradle</h1>

<h3>Login</h3>
<form method="post">
    {% csrf_token %}
    {{login_form.as_p}}
    <input type="submit" value="Login">
</form>

<h3>Sign up</h3>
<form method="post">
    {% csrf_token %}
    {{sign_up_form.as_p}}
    <input type="submit" value="Sign up">
</form>

templates/users/base_main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} {% endblock %}</title>
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
  <link rel="stylesheet" href= " {% static 'css/style.css' %}" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
  {% block custom_scripts_n_links %}{% endblock %}
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar">
    <div class="inner-width">
      <div id="logodiv">
        {% if request.user.usertype == 1 %} <!--href will not work in img tag, so enclose img tag in 'a' tag-->
        <img src="{% static 'images/Cc.png' %}" href="{% url 'candidates:home' %}" alt="CareerCradle Logo">
        <!--<a  class="logo"></a>-->
        {% endif %}
        {% if request.user.usertype == 0 %}
        <img src="{% static 'images/Cc.png' %}" href="{% url 'recruiters:home' %}" alt="CareerCradle Logo">
        <!--<a  class="logo"></a>-->
        {% endif %}
      </div>
      <button class="menu-toggler">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <div class="navbar-menu">
        {%	if	request.user.is_authenticated	%}	
        <h3><strong>{{request.user.email}}</strong></h3>
        {% endif %}
        
        {% if request.user.usertype == 1 %}
        <a href="{% url 'candidates:home' %}">Home</a>
        <a href="{% url 'candidates:dashboard' %}">Dashboard</a>
        <!--<a href="#Profile">Profile</a>-->
        {% endif %}
        {% if request.user.usertype == 0 %}
        <a href="{% url 'recruiters:home' %}">Home</a>
        <a href="{% url 'recruiters:jobs_posted' %}">Dashboard</a>
        <!--<a href="#Profile">Profile</a>-->
        {% endif %}
        <a href="{% url 'users:aboutus' %}">About</a>
        <a href="{% url 'users:contactus' %}">Contact</a>  
        <a href="{% url 'account_logout' %}">Logout</a>
      </div>
    </div>
  </nav>

  {% block Welcome_block %}
  <!-- Home -->
  <section id="home">
    <div class="inner-width">
      <div class="content">
        <h1>Career Cradle</h1>
        {% if request.user.usertype == 1 %}
        <div id="candidate_tagline">
          <h2>**Make </h2>
        </div>
        {% endif %}
        {% if request.user.usertype == 0 %}
        <div id="recruiter_tagline">
          <h2>**Let's </h2>
        </div>
        {% endif %}
      </div>
    </div>
  </section>
  {% endblock %}

  <!--content-->
  <div>{% block content %} {% endblock %}</div> 

  <!-- Footer -->
  <footer>
    <div class="inner-width">
      <div class="copyright">
        &copy; 2021 | Created & Designed By <a href="#"><strong>Career Cradle Team</strong></a>
      </div>
    </div>
  </footer>

  <!-- Go Top BTN -->
  <button class="goTop fas fa-arrow-up"></button>

</body>
</html>

templates/users/contact.html
{% extends 'users/base_main.html' %}
{% load  static %}

{%	block	title	%}Contact{%	endblock	%}

{% block custom_scripts_n_links %}
<link rel="stylesheet" href= " {% static 'css/contact.css' %}" />
{% endblock %}

{%block Welcome_block %}{% endblock %}

{% block content%}

    <section class="contact">
        <div class="content">
            <h2>Contact Us</h2>
        </div>
        <div class="container">
            <div class="contactInfo">
                <div class="box">
                    <div class="icon"><i class="" aria-hidden="true"></i></div>
                    <div class="text">
                        <h3>Address</h3>
                        <p>223 Mine City Road,<br>Ramoji,Hyderabad,<br>22875</p>
                    </div>
                </div>
                <div class="box">
                    <div class="icon"><i class="" aria-hidden="true"></i></div>
                    <div class="text">
                        <h3>Phone</h3>
                        <p>11125-55432</p>
                    </div>
                </div>
                <div class="box">
                    <div class="icon"><i class="" aria-hidden="true"></i></div>
                    <div class="text">
                        <h3>Email</h3>
                        <p>carrear-cradle921@gmail.com</p>
                    </div>
                </div>
            </div>
            <div class="contactForm">
                <form>
                    <h2>Send Message</h2>
                    <div class="inputBox">
                        <input type="text" name="" required="required">
                        <span>Full Name</span>
                    </div>
                    <div class="inputBox">
                        <input type="text" name="" required="required">
                        <span>Email</span>
                    </div>
                    <div class="inputBox">
                        <textarea required="required"></textarea>
                        <span>Type your Message...</span>
                    </div>
                    <div class="inputBox">
                        <input type="submit" name="" value="Send">
                    </div>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

templates/users/navfoot.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href= " {% static 'css/navfoot.css' %}" />
    <link rel="stylesheet" href="navfoot.css">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    {% block custom_scripts_n_links %}{% endblock %}
</head>
<body>
     
    <nav id="navbar">
        <div id="logo">
            <img src="{% static 'images/Cc.png' %}" alt="Career-Cradle.com" width="70" height="70">
        </div>
        <ul>
            <li class="item"><a href="#home">Home</a></li>
            <li class="item"><a href="#">Dashboard</a></li>
            <li class="item"><a href="#">Profile</a></li>
            <li class="item"><a href="#">About</a></li>
            <li class="item"><a href="#">Contact</a></li>
        </ul>
    </nav>

    <div>{% block content %} 
          {% endblock %}</div> 

    <!-- Footer -->
  <footer>
    <div class="inner-width">
      <div class="copyright">
        &copy; 2021 | Created & Designed By <a href="#"><strong>Career Cradle Team</strong></a>
      </div>
    </div>
  </footer>

   
</body>
</html>

templates/users/usertype.html
{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    {{ usertype_form|crispy }}
    <input type="submit" value="Save">
</form>